name: Python

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      # 执行python 命令
      - run: python3 make.py
